### ISSUE TITLE
How to dealwith styles?

### ISSUE THREAD

**Issue by linonetwo** [cereallarceny/cra-ssr#10]
Antd imports its style for every component.
Ignoring style import will cause antd failed to be beautiful.

Any way to support importing css or sass?

**Comment by linonetwo** [comment]
Strangely, styles just work fine, I don't quite understand why.

**Comment by cereallarceny** [comment]
It's because they're ignored in the main server entrypoint file: https://github.com/cereallarceny/cra-ssr/blob/master/server/index.js#L14

**Comment by marinav** [comment]
Hi, first, thank you very much for your great work ! It's really awesome. 

I also have a problem with styles. I import them in every component I have, so they are loaded after the js. So during 1/2 sec my website is really ugly.

Is it a bad practise to import each css in it's component ? What am I suppose to do to load them before js ? 

Thank you very much :)
