### ISSUE TITLE
Using ignore-styles breaks Base64 encoded image

### ISSUE THREAD

**Issue by linonetwo** [cereallarceny/cra-ssr#14]
There is a small png in my site, so CRA inline it with Base64 encoding:

```html
<img alt="Language" src="data:image/png;base64,iVBORw0KGgoAAA........54MkQ4wAAAABJRU5ErkJggg==" style="width: 20px; height: 20px; margin-right: 5px;">
```

It works fine if I run my site using `http-server ./build`.

But if run it with SSR, the image will turn into:
```html
<img alt="Language" src="/static/media/translate.e24f196b.png" style="width:20px;height:20px;margin-right:5px">
```
So breaks image.

**Comment by linonetwo** [comment]
Basic idea is check img size:
```js
const fs = require('fs');
...

  const stats = fs.statSync(filename);
  const fileSizeInBytes = stats.size / 1024;
  if (fileSizeInBytes <= 10) return ignoreStyles.noOp();
```
But simply using this cause img tag to be:
```html
<img style="width:20px;height:20px;margin-right:5px" alt="Language" src="[object Object]">
```

**Comment by cereallarceny** [comment]
@linonetwo Instead of checking file size, which may change in CRA in the future... is there a way to check for the source starting with `data:image`?  To me, this would be more reliable.

**Comment by linonetwo** [comment]
`data:image` is added by CRA in the build time, and then CRA just delete that image.
So we have no way to know whether CRA will inline that image in the SSR server (after CRA build), except to check the image size.

**Comment by cereallarceny** [comment]
No, I meant to check the `src` attribute on the `<img />`, but it seems that's not possible until after build.

**Comment by linonetwo** [comment]
Yes, I think the only way is to stay focus on what CRA is doing, just follow the same specific method as CRA.

**Comment by cereallarceny** [comment]
Feel free to submit a PR @linonetwo!
