### ISSUE TITLE
Needless data fetching on client side

### ISSUE THREAD

**Issue by DavidKloucek** [cereallarceny/cra-ssr#16]
When I load profile page, [frontload](https://github.com/cereallarceny/cra-ssr/blob/master/src/app/routes/profile/index.js#L12) is called again in the browser, but it is useless because I am using SSR .

Does anybody know where is the problem?

**Comment by hugominas** [comment]
Same here, first of, thanks for the amazing work @cereallarceny . 

I have used CRA-SSR on some production applications and everything is working amazing.

@DavidKloucek I guess this is a feature not bug but I agree as it should not load the same resource twice [https://github.com/cereallarceny/cra-ssr/blob/7dbdffa76ccdc981625769278028b1ffc973f8fc/src/index.js#L16](url)

**Comment by cereallarceny** [comment]
I believe this is an issue you should create with [React Frontload](https://github.com/davnicwil/react-frontload).  Closing because it's not pertinent here.
