### ISSUE TITLE
Import fonts file

### ISSUE THREAD

**Issue by huyb1991** [cereallarceny/cra-ssr#18]
Here's my component for icon font:
```
// styles.js

import { injectGlobal } from 'styled-components'

import iconEOT from './assets/fonts/icons.eot'

@font-face {
    font-family: 'icons';
    src:  url('${iconEOT}');
    src:  url('${iconEOT}#iefix') format('embedded-opentype');
    font-weight: normal;
    font-style: normal;
  }
```

App crashed when run serve: `npm run serve`

>SavingsFrontend\node_modules\babel-core\lib\transformation\file\index.js:558
      throw err;
      ^
>SyntaxError: SavingsFrontend/src/app/assets/fonts/icons.eot: Unexpected character ''

**Comment by cereallarceny** [comment]
We don't have support for `styled-components`.  If you'd like to add this, please submit a PR.  Closing as it's "off topic".
