### ISSUE TITLE
Code-splitting not always resolving resources in localhost

### ISSUE THREAD

**Issue by cereallarceny** [cereallarceny/cra-ssr#32]
**NOTE: This issue is only affected on localhost**

@arturparkhisenko I'm not sure this is related to the previous script replace PR, because I've seen this with the original `master` branch as well.  It seems as though we're not taking into account the hostname in the `<script>` tags.  However... the resource loads correctly both on localhost and in the deployed environment.  Any thoughts?

<img width="528" alt="screen shot 2018-10-04 at 3 40 29 pm" src="https://user-images.githubusercontent.com/1297930/46502269-5dd1b080-c7ed-11e8-9b3d-7f06fc4ecc01.png">

**Comment by arturparkhisenko** [comment]
@cereallarceny i'll check it in a few hours.

**Comment by arturparkhisenko** [comment]
@cereallarceny can't reproduce, can you provide the steps? I've just updated my fork from `master`, reinstalled dependencies with `npm` and both `start`, `serve` works good. Using this auto-opened url: `http://localhost:3000/`

**Comment by cereallarceny** [comment]
Yeah that should be it.  You should be able to reproduce it from running `yarn build && yarn serve`.  Does that not trigger the error?

**Comment by arturparkhisenko** [comment]
@cereallarceny today i'll test again, note only that i'm using npm (i don't have yarn).

**Comment by arturparkhisenko** [comment]
@cereallarceny works, we could wait or re-open if will be reproducible.

**Comment by cereallarceny** [comment]
I'm good to close it.
