### ISSUE TITLE
Can I build an application ssr with livereload?

### ISSUE THREAD

**Issue by fedorovsky** [cereallarceny/cra-ssr#4]
Can I build an application ssr with livereload?

**Comment by cereallarceny** [comment]
Only if you had the build process running in the background.  SSR works from the `/build` directory, so you would need to clear that out, rebuild, and restart the server every time you save a file.  I would likely say that isn't possible.

However, as you can tell in the `package.json` file, I've allowed you to run in either "server" mode or "client" mode (which does have live-reloading via CRA).  Run `yarn serve` to see it running SSR in development mode, `yarn deploy` to see it running SSR in production mode, and `yarn start` for regular development (no SSR, but with hot reloading).
