### ISSUE TITLE
ReferenceError: window is not defined when i use      window.onscroll = function(){ ssr

### ISSUE THREAD

**Issue by heshamelmasry77** [cereallarceny/cra-ssr#45]
can somebody help me fix this problem 
```
 window.onscroll = function(){

      console.log ('test');
```

**Comment by evgenyantipin** [comment]
@heshamelmasry77 try this one
import root from "window-or-global";
root.onscroll = function(){
  console.log ('test');
}

**Comment by cereallarceny** [comment]
This is because `window` doesn't exist on the server.  It cannot be used for server-side rendering.
