### ISSUE TITLE
Helmet dynamic data not working on Facebook debugger?

### ISSUE THREAD

**Issue by phucvo0709** [cereallarceny/cra-ssr#49]
I use your source to develop, but currently it has a problem that dynamic data in the helmet I transmit but on the facebook debugger it takes the default helmet? I want to ask you how to update dynamic content now?

**Comment by francisrod01** [comment]
I think this is related with this topic #35

**Comment by phucvo0709** [comment]
> I think this is related with this topic #35

have you repaired it yet?
