### ISSUE TITLE
SSR is not working

### ISSUE THREAD

**Issue by dineshswamy** [cereallarceny/cra-ssr#5]
I did `yarn build and yarn serve`. I get only javascript  not  HTML

![screen shot 2018-02-27 at 5 44 12 pm](https://user-images.githubusercontent.com/3234767/36728155-d988bbf6-1be5-11e8-8ec4-177a691ad213.png)

**Comment by gadfil** [comment]
Hi, I have this issue too
I check https://cra-ssr.herokuapp.com/ and see only js  

`<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000"><link rel="manifest" href="/manifest.json"><link rel="shortcut icon" href="/favicon.ico"><title>React App</title><link href="/static/css/main.4df55bac.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script type="text/javascript" src="/static/js/main.c66c0e3a.js"></script></body></html>`

**Comment by Bramas** [comment]
If faced the same problem, but here's why:
If javascript is enable during the first load of the page, the serviceWorker will be registered and loading the page will result in using cached data in priority (thus index.html, which is an empty page).
To see that ssr is actually working, either open incognito, disable js **and then** open the page, or just curl https://cra-ssr.herokuapp.com/ to see it's actually working.
