### ISSUE TITLE
How to prevent first load?

### ISSUE THREAD

**Issue by phucvo0709** [cereallarceny/cra-ssr#50]
I'm having a problem, my local code works fine, but on the server it has a first load error but I don't know where the error comes from, I need help how to prevent pre-loading!

![untitled](https://user-images.githubusercontent.com/35060381/51968708-37730780-24a5-11e9-9ed9-1de2872dc5fd.png)
screen i need to prevent

demo: http://web-staging.beaudy.vn

**Comment by cereallarceny** [comment]
Sorry, if this isn't a bug report, I can't help on individual websites.  Closing.

**Comment by heshamelmasry77** [comment]
I will help you @phucvo0709  It been a problem for me as well. What i did that i decided to move to next js. I had a problem with the first load and the style sheets not load correctly something go wrong when the project gets big.

**Comment by phucvo0709** [comment]
> I will help you @phucvo0709 It been a problem for me as well. What i did that i decided to move to next js. I had a problem with the first load and the style sheets not load correctly something go wrong when the project gets big.

I sent a mail, looking forward to your help!
