### ISSUE TITLE
Helmet tags not shown

### ISSUE THREAD

**Issue by sach185** [cereallarceny/cra-ssr#55]
I have built an app following the tutorial.
Anytime the page reloads, I make an API call to fetch some data. I have to wait for the response of this API before accessing any route so I am showing a Loader till the API response is received. However doing this causes react-helmet tags to be empty. When I remove the Loader it works fine. 
Any help as to why this happens and how to fix this would be really appreciated.
Thanks!!

**Comment by francisrod01** [comment]
In this case, you need to update the store by your own way on the server-side.
I mean, you need to catch the data by server-side first and then pass it by server-side to front-side.
I hope I've helped.

**Comment by sabitertan** [comment]
Depends on how you attach/detach your Loader you may break "state" of the App. Theoratically you can define a "isAPILoading" property and check that before changing state. When you are loading data you should set isApiLoading:true and when you are done isApiLoading:false.
