### ISSUE TITLE
One command to ssrify any CRA project ?

### ISSUE THREAD

**Issue by revskill10** [cereallarceny/cra-ssr#7]
How about create a node command to `ssrify` an existing CRA project ? , something like:
```
ssrify mycrafolder
```
->
```
This repo
```

The benefit is that, when all dependencies got upgraded, we can only upgrade that cli tool to regenererate CRA project again.

**Comment by cereallarceny** [comment]
This could be done @checkraiser - feel free to submit a PR if you're inclined.  I feel it may require a slight bit of configuration.  I'm open to this though.

**Comment by linonetwo** [comment]
It could be something like react-snap but works better with dynamic data.

**Comment by linonetwo** [comment]
But I would be complicated.
People are using different toolchains. For me, I need to set up SSR for `styled-components` and `@rematch/core` and `i18next`, I have to follow each package's document.
I think it's impossible to have a cli to make SSR out of box supporting different toolchains.

**Comment by cereallarceny** [comment]
It's definitely pretty unreasonable to encounter every option, yes.  However... maybe what could happen is a CLI that does the following:

1. Asks for what parts of SSR you'd like to set up (code splitting, component-specific preloaded data, styled components, etc.)
2. CLI does as much setup as possible
3. CLI then tells you all the things it couldn't do automatically and provides manual examples of how to do each.

Alternatively... we could just build a CLI that only scaffolds a new CRA project (or adds another one with instructions on how you might finish yourself).

**Comment by checkraiser** [comment]
You can always make default config, then provide arguments options for people to pick their own choice or override themselves.

**Comment by cereallarceny** [comment]
Yes @checkraiser - but this gets incredibly complicated to handle each particular circumstance.  We'ld have to add support for a variety of different situations... CSS?  SASS?  LESS?  CSS Modules?  Styled Components?  Other methods?  Each of those may be handled uniquely from the next.  And quite frankly, that's just CSS.  The CLI could get out of hand very quickly and be pretty tough to maintain.

**Comment by antonybudianto** [comment]
Hi, you might be looking for https://github.com/antonybudianto/cra-universal :)

**Comment by cereallarceny** [comment]
Closing this as it's out of scope.
