### ISSUE TITLE
styled-components?

### ISSUE THREAD

**Issue by jlarmstrongiv** [cereallarceny/cra-ssr#8]
Hi,

I just finished reading your tutorial on Medium; thank you.  It’s a big help!  Here’s a newbie question:

I am wondering how to integrate cra-ssr with the styled-components package.  I was reading their [documentation](https://www.styled-components.com/docs/advanced#server-side-rendering), but I just wasn’t sure where in the hierarchy their component should go:
```jsx
// current renderToString
  <Loadable.Capture report={m => modules.push(m)}>
    <Provider store={store}>
      <StaticRouter location={req.url} context={context}>
        <Frontload isServer>
          <App />
        </Frontload>
      </StaticRouter>
    </Provider>
  </Loadable.Capture>

// their renderToString
  <StyleSheetManager sheet={sheet.instance}>
    <YourApp />
  </StyleSheetManager>

const styleTags = sheet.getStyleTags() // or sheet.getStyleElement()
```
I’m also not entirely sure if their wrapper component injects the style tags into the head on its own.  It looks like express is still responsible for passing those to the page.

There’s another method ([article](https://medium.com/styled-components/the-simple-guide-to-server-side-rendering-react-with-styled-components-d31c6b2b8fbf)) which takes those style tags into account:  
```js
  const sheet = new ServerStyleSheet(); // <-- creating out stylesheet

  const body = renderToString(sheet.collectStyles(<App />)); // <-- collecting styles
  const styles = sheet.getStyleTags(); // <-- getting all the tags from the sheet

  const title = 'Server side Rendering with Styled Components';

  res.send(
    Html({
      body,
      styles, // <-- passing the styles to our Html template
      title
    })
  );
```
To add that to your current setup, I would assume that styles would be passed into the page HOC and react-helmet would be configured to add the tags to the head?

**Comment by listatt** [comment]
Just wrap your <App/> component

**Comment by jlarmstrongiv** [comment]
Wish it were that easy!  Inside `server/loader.js`, a few edits need to be made.   

First, styled-components needs to import it’s ServerStyleSheet at the top of the file:
```jsx
import { ServerStyleSheet } from 'styled-components'
```

Second, the frontloadServerRender function needs to return and destructure both the routeMarkup and the styleTags:

```jsx
      frontloadServerRender(() => {
        const sheet = new ServerStyleSheet();
        const routeMarkup = renderToString(sheet.collectStyles(
          <Loadable.Capture report={m => modules.push(m)}>
            <Provider store={store}>
              <StaticRouter location={req.url} context={context}>
                <Frontload isServer>
                  <App />
                </Frontload>
              </StaticRouter>
            </Provider>
          </Loadable.Capture>
        ))
        const styleTags = sheet.getStyleTags();
        return { routeMarkup, styleTags };
      }).then(({ routeMarkup, styleTags }) => {
```

Third, styleTags needs to be added to the injectHTML function:  
```jsx
          const html = injectHTML(htmlData, {
            …
            state: JSON.stringify(store.getState()).replace(/</g, '\\u003c'),
            styleTags
          });
```

Fourth, styleTags needs to be destructured from the injectHTML function and included in the </head> with the meta tags.  
```jsx
  const injectHTML = (data, { html, title, meta, body, scripts, state, styleTags }) => {
    data = data.replace('<html>', `<html ${html}>`);
    data = data.replace(/<title>.*?<\/title>/g, title);
    data = data.replace('</head>', `${styleTags}${meta}</head>`);
```

Hopefully this’ll help anyone else who comes along 🙂 feel free to make suggestions
