### ISSUE TITLE
Replace hydrate statement

### ISSUE THREAD

**Issue by cereallarceny** [cereallarceny/cra-ssr#9]
I saw some code over at [React Snap](https://github.com/stereobooster/react-snap) that inspired me here.  We should investigate whether or not this can replace us sniffing `process.env` for the production environment... which is not necessarily indicative of SSR.  One could easily run `yarn serve` in `development` mode.

```jsx
const rootElement = document.getElementById('root');

if (rootElement.hasChildNodes()) {
  hydrate(<App />, rootElement);
} else {
  render(<App />, rootElement);
}
```

**Comment by ns23** [comment]
Can I work on this issue?

**Comment by cereallarceny** [comment]
By all means!  Go for it.  Send a PR when you're done.

**Comment by cereallarceny** [comment]
You got it boss (@arturparkhisenko)!
